### ISSUE TITLE
Not able to add playlist

### ISSUE THREAD

**Issue by LukasHe** [confirm/mopidy-pummeluff#12]
At the moment I am not able to start playing a whole playlist, just single songs/streams.
I am not sure if it is supported via the *Tracklist* class and it is simply not working for my setup, or if it is not supported at all.

```
    {
        "tag_class": "Tracklist",
        "uid": "86543824",
        "alias": "detektorFM Musik",
        "parameter": "https://detektor.fm/stream/mp3/musik/"
    },
    {
        "tag_class": "Tracklist",
        "uid": "EB7CD322",
        "alias": "Couch",
        "parameter": "m3u:couch.m3u8"
    }
```
Here `detektorFM Musik` works but `Couch` does not.

**Comment by domibarton** [comment]
@LukasHe I've never tried that. I need to reproduce it and probably read / reverse engineer the mopidy API again :)

**Comment by domibarton** [comment]
So I did some reverse engineering and I think this is related to [this issue](https://github.com/mopidy/mopidy/issues/1548). IMHO it's a bit weird to do all this business logic checks on each client rather than on the API backend itself, but yeah, that's how it works.

I'll let you know when I've refactored the code!

**Comment by domibarton** [comment]
@LukasHe I think I sorted it out in ebce639bf317745485c079964279deb48bbc7554. Please try either the [v2.1.0 git tag](https://github.com/confirm/mopidy-pummeluff/releases/tag/v2.1.0) or the released [Mopidy-Pummeluff 2.1.0 PyPI package](https://pypi.org/project/Mopidy-Pummeluff/2.1.0/).

**Comment by domibarton** [comment]
@LukasHe didn't got a response, thus I'm closing the issue. Feel free to re-open it if you still having problems with playlists :)

**Comment by LukasHe** [comment]
@domibarton Thanks for the changes. Now it works flawlessly for me. So the issue can stay closed.

**Comment by domibarton** [comment]
@LukasHe Awesome, thanks for the reply. I hope everything else works as expected :) HF!
