### ISSUE TITLE
lib pi-rc522 seems to be broken

### ISSUE THREAD

**Issue by alpex8** [confirm/mopidy-pummeluff#17]
Hi,

the library latest available version on pypi of pi-rc522 seems to be broken according to the project https://github.com/STEMinds/RC522-Python. The mentioned reason are changes on "changes in the raspberry pi system".
I can confirm this. I have a MiFare RC522 Reader which doesn't work anymore on a Pi 3b+. However the much older library https://github.com/mxgxw/MFRC522-python is still working. I would assume that it's not just me who is affected.

pi-rc522 which is used here doesn't seem to get a new version on pypi, so would it be an option to switch to another library?

Is https://github.com/mxgxw/MFRC522-python an option? pi-rc522 was forked from it, it is still working, but it is also quite dead.
https://github.com/STEMinds/RC522-Python seems alive at least for now but it comes with some dependency lib that isn't available on pypi and needs to be installed manually. So is this an option?

**Comment by domibarton** [comment]
I need to check the new library first. Most of the RC522 libraries are missing the interrupt handling (see IRQ pin), which means they won't work - at least not with the current setup.

**Comment by domibarton** [comment]
I did a completely new setup on a RaspberryPi 3. The code still works and I've no issue reading the RFID tags. Can you tell me which RaspberryPi version you've?
