### ISSUE TITLE
RFID tags can only be read 2-3 times

### ISSUE THREAD

**Issue by hayribakici** [confirm/mopidy-pummeluff#20]
Hi,
thank you for this extension. I have a problem, however, with reading the tokens. When mopidy is started, pummeluff is able to read the tags, but only for a couple of times. After 2-3 successful reading attempts (with `sudo journalctl -u mopidy`), it just doesn't read anything from any rfid-tag and `journalctl` doesn't output anything. Is there something I am doing wrong or anywhere I can get more log information to see where the issue might arise?

**Comment by domibarton** [comment]
Mhm I need to update my mopidy first and then I can test it again. Probably this is related to #17 ?

**Comment by alepee** [comment]
Could you publish `journalctl -y mopidy` result? I got something similar, but it seems to be caused by `Mopidy-Spotify`, it prevented execution of any other resource when authenticate to Spotify Web API.
